### ISSUE TITLE
I have withdrawal my neblio coin on 16 FEb now i dont have incoming deposit 

### ISSUE THREAD

**Issue by innnzzz6** [NeblioTeam/neblio#100]
http://explorer.nebl.io/tx/6c50e6be956a7fba4734a09c484c15440c1c31d51367ddef2b3884dfc0b89c7f

I have withdrawal on 16FEB now I don’t have incoming deposit .. my neblio Cryptopia address :NMMGp5xJRreprWtSV1GuFr4bC8zorD8QbY sent 111.93637442 nebl to my neblio qt but my coin move to the address :NemT2vxEaHBZ6ct3qfGzGHjDP2uWJbnWUL  

Please check it for me ..thanks support 

I need return my coin to my address

**Comment by NeblioTeam** [comment]
This sounds like a question for Cryptopia support. Github is not a support forum.

**Comment by innnzzz6** [comment]
But support ..told me I should contact platform to nebl support  .. how to
contact platform ..thanks support

**Comment by innnzzz6** [comment]
>
> Hi ..neblio support team ..
>
 I have a questions for get NTP1 MY Address have send NEBL to Binance
exchange holding amount 111 NEBL .. i should send amount transaction Neblio
Orion for receive  NTP1 token ??  1. Or 111 I don’t know about this ..
please let me know .. how to receive ..thanks support

innnzzz6@gmail.com

**Comment by innnzzz6** [comment]
http://explorer.nebl.io/api/getrawtransaction?txid=%206c50e6be956a7fba4734a09c484c15440c1c31d51367ddef2b3884dfc0b89c7f&decrypt=1
