### ISSUE TITLE
Update to Raspberry Pi Install Script for no Xserver Present

### ISSUE THREAD

**Issue by XCBatman** [NeblioTeam/neblio#101]
**Issue**: Auto-start of Neblio-qt fails when running the install script

**Description**: When running the Raspberry Pi install script the Nebli-qt wallet is started automatically. However, for users that are running command-line only, this will fail. 

**Recommendation**: Check if `~/Desktop` directory exists. If it does, execute Neblio-qt; if it does not, then it's safe to assume that the user is not using a GUI and either `nebliod -daemon` should be started, or nothing. 

**Version**: nebliod 1.4.0.0

**Comment by NeblioTeam** [comment]
This should be fixed in the NEBL-Pi repo now.
