### ISSUE TITLE
Support Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by forall** [NeblioTeam/neblio#122]
Hi,
After upgrade linux mint from 18.3 do the 19, neblio-qt stopped working with depedence problem.
./neblio-qt 
./neblio-qt: /usr/lib/x86_64-linux-gnu/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by ./neblio-qt)

**Comment by TheQuantumPhysicist** [comment]
I use Ubuntu 18.04 with no problem. Perhaps you should recompile Neblio (have you compiled it yourself?).

Also try this and see if it helps: `sudo apt-get install libcurl4-openssl-dev`.

**Comment by forall** [comment]
Hi,

I have problem to recompile Neblio, because I get some error. Which version gcc are you use?
Did you compile with debian method?

**Comment by TheQuantumPhysicist** [comment]
I use the default version that comes with Ubuntu, 7.3.0. I also use clang some times and that works. Yes, I use the same method as Debian.

**Comment by TheQuantumPhysicist** [comment]
Please run the following in the root directory of neblio:

```
mkdir build
cd build
qmake ..
make
```

**Comment by forall** [comment]
I run that command but I still have error:
<code>
rpcrawtransaction.o ../../wallet/rpcrawtransaction.cpp
g++ -c -pipe -fstack-protector-all -D_FORTIFY_SOURCE=2 -Wl,-z,relro -Wl,-z,now -O2 -std=gnu++11 -D_REENTRANT -fdiagnostics-show-option -Wall -Wextra -Wno-ignored-qualifiers -Wformat -Wformat-security -Wno-unused-parameter -Wstack-protector -fPIC -DQT_GUI -DBOOST_THREAD_USE_LIB -DBOOST_SPIRIT_THREADSAFE -DQT_DISABLE_DEPRECATED_BEFORE=0 -DBOOST_ASIO_ENABLE_OLD_SERVICES -DUSE_UPNP=1 -DSTATICLIB -DUSE_DBUS -DHAVE_BUILD_INFO -DLINUX -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_DBUS_LIB -DQT_CORE_LIB -I../../wallet -I../../wallet/json -I../../wallet/qt -I../../wallet/leveldb/include -I../../wallet/leveldb/helpers -isystem /usr/include/libdb4/ -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtDBus -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -Ibuild -isystem /usr/include/libdrm -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o build/overviewpage.o ../../wallet/qt/overviewpage.cpp
../../wallet/qt/overviewpage.cpp:90:28: fatal error: overviewpage.moc: There is no such file or directory
</code>

**Comment by NeblioTeam** [comment]
No recent update.
