### ISSUE TITLE
Document Neblio RPC commands in detail

### ISSUE THREAD

**Issue by danifr** [NeblioTeam/neblio#129]
It took me a while to figure out how to lock my wallet. In order to see the list of available commands I needed to take a look at the wallet's source code:

https://github.com/NeblioTeam/neblio/blob/ec92c58a24bf052549d203e1197961ad676e339e/wallet/bitcoinrpc.cpp#L253

Thanks!

**Comment by TheQuantumPhysicist** [comment]
Doesn't the command `help` give the list of available commands?

**Comment by danifr** [comment]
Hmm yes, it does.

So:
```
nebliod help    --> List of available commands
nebliod --help  --> List of available params
```
Shouldn't this be documented somewhere?
Thanks!
