### ISSUE TITLE
Wallet doesn't open; Error "Assertion Failed"

### ISSUE THREAD

**Issue by g4usat** [NeblioTeam/neblio#133]
Hi, When I try to open wallet, it's throwing "Assertion Failed" and doesn't open whether I Retry or Ignore.

File: src/kernel.cpp, Line 378
Expression: pindex->pprev || pindex->GetBlockHash() == (!fTestNet ? hashGenesisBlock : hashGenesisBlockTestNet)

I've deleted all the files except wallet.dat as mentioned in the solution of previous issue reported by others. But it still doesn't work. Am still getting the same issue. Attaching the screenshot for your reference. Appreciate if you could help me fix this ASAP.

Thanks!
![neblio wallet error](https://user-images.githubusercontent.com/36013227/45911329-5ff04400-bdd7-11e8-886a-48e6631d32d5.PNG)

**Comment by NeblioTeam** [comment]
Make sure you are deleting the right files.

You can find the right folder on Windows by typing `%APPDATA%` into Windows Explorer

Delete everything in that folder other than wallet.dat and potentially neblio.conf if it exists.

**Comment by g4usat** [comment]
Yes, I do know the folder location and have deleted ALL files but not Folders and wallet.dat. Attaching the screen shot of the folder. But, it doesn't work. I would appreciate if you can take a moment and see why and what's going on and let me know the solution. Am afraid if all my tokens are safe and how do I make the wallet work. 
![neblio wallet error1](https://user-images.githubusercontent.com/36013227/45920767-ec017a80-be6e-11e8-98c4-48b3154f30fa.PNG)

**Comment by NeblioTeam** [comment]
You need to delete the database and txleveldb folders as well. Then when you restart the wallet it will sync the blockchain from scratch. After it is fully synced you will see your NEBL.

**Comment by ILoveSoftware** [comment]
As feedback, I just had the same issue, found this interaction, and it solved my problem. Thanks for providing these references.
