### ISSUE TITLE
Lower right icons are small and difficult to see

### ISSUE THREAD

**Issue by Joeyfat** [NeblioTeam/neblio#134]
Hello
I'm currently staking in the wallet but find the staking and encryption symbols etc. in the bottom right hand of the screen way to small, they are difficult to see and hard to keep the mouse on. It would be great if you could make the symbols larger. Kind regards  Peter (UK)

**Comment by NeblioTeam** [comment]
Peter,

Could you please provide a screenshot of how this looks for you? Feel free to edit out any balance or addresses from the screenshot.

Please also let us know your OS and screen resolution. As far as I know this is not an issue for other users.

**Comment by NeblioTeam** [comment]
Closing due to lack of info. Feel free to re-open.
