### ISSUE TITLE
Make 'Amount' column on the transactions tab larger

### ISSUE THREAD

**Issue by Joeyfat** [NeblioTeam/neblio#135]
one other issue, the "Amount" column on the transactions page of the wallet is too narrow and it is not possible to re-size it like the other columns. This is making it difficult to read your stake awards and it makes the wallet look amateurish.

**Comment by NeblioTeam** [comment]
After looking at the code, the easiest and most efficient fix here will be to make the 'Amount' column 20% wider. If we need to make it even wider in the future, we can.
