### ISSUE TITLE
Staking taking a long time

### ISSUE THREAD

**Issue by jdriscol27** [NeblioTeam/neblio#138]
I usually get stake rewards a couple times a week.  It's been 8 days since the last reward, which hasn't happened in over a year.  It's been showing the expected time for coin reward as 1 day for the past 5 days.  Any insight?

**Comment by NeblioTeam** [comment]
We try to reserve GitHub issues for bug reports, please feel free to email us at any time for support requests. 

Stake rewards can be highly variable, ensure you are fully synced and on the latest version (v1.5.2 at the time of this writing). Email us if you require further assistance.
