### ISSUE TITLE
Neblio Wallet Staking Issue (V1.5.2)

### ISSUE THREAD

**Issue by g4usat** [NeblioTeam/neblio#139]
Hi, I bought some NEBL on 9/8/18 and they are on Neblio wallet ever since then. But, I haven't received any staking rewards until now. I've recently upgraded wallet to v1.5.2 as well. Am always keeping the wallet unlocked and available for staking. However, it always says "staking", weight as '6435' and network weight now showing as '40982557' earlier it was some number in 30M+ and the expected time to earn reward earlier was 6 or 7 days but now it's showing as 8 days. Am not able to get what's the issue and why my wallet shows weight as same number 6435 from time eternal and the days keep increasing even after my wallet is available unlocked. Can you please look into this issue and help me with the resolution asap. Thanks a lot in advance!

I just noticed that under 'Transactions' tab, I see a staking reward of 5NEBL with "?" and it says "staking reward rejected-Another user staked reward block first"? that means is it pure luck to get staking rewards despite keeping wallet unlocked and available 24/7. How do we know that which user is the first one? and why someone should get reward when my wallet is staking? This is ridiculous and doesn't make any sense?? Or is there anything that I need to do which am missing? Pls help with this whole staking issue mess.

**Comment by NeblioTeam** [comment]
We reserve GitHub issues for bug reports and new feature requests, not support.

You can read more about staking and how it works, here https://nebl.io/2017/07/01/staking-explained/ and https://nebl.io/learn/why-was-my-stake-rejected/

If you still have questions you can contact support at https://nebl.io/contact
