### ISSUE TITLE
Investigate Performance Improvements with HUGE wallets

### ISSUE THREAD

**Issue by NeblioTeam** [NeblioTeam/neblio#146]
It appears that we currently scan for NTP1 tokens on every block, even on blocks that contain no transactions to or from any addresses in our wallet.

On huge wallets, this can lead to sluggishness (especially seen on RPi). 

We should investigate to see if we can reduce this scanning to only when blocks contain transactions that affect an address in our wallet.

**Comment by NeblioTeam** [comment]
Moving this from the Beta milestone to the Release milestone since it is highly unlikely many users will hit this.

**Comment by DICKWJC** [comment]
[Electrum Neblio](https://www.electrumneblio.org)
[Electrum Neblio Wallet](https://www.electrumneblio.org)
[Electrum Wallet Neblio](https://www.electrumneblio.org)
[Neblio Electrum](https://www.electrumneblio.org)
[Neblio Electrum Wallet](https://www.electrumneblio.org)
[Neblio Wallet Electrum](https://www.electrumneblio.org)
[Electrum Nebl Wallet](https://www.electrumneblio.org)
[Electrum Nebl](https://www.electrumneblio.org)
[Electrum Wallet Nebl](https://www.electrumneblio.org)
[Nebl Electrum](https://www.electrumneblio.org)
[Nebl Electrum Wallet](https://www.electrumneblio.org)
[Nebl Wallet Electrum](https://www.electrumneblio.org)

**Comment by TheQuantumPhysicist** [comment]
This was already visited and fixed.
