### ISSUE TITLE
Orphan blocks appear and prevent syncing

### ISSUE THREAD

**Issue by TheQuantumPhysicist** [NeblioTeam/neblio#155]
Under some random circumstances, the blockchain syncing process stops, and all blocks are deemed orphan blocks.

This was noticed first during debugging when an exception was thrown during syncing.

**Comment by david4neblio** [comment]
This happened to me when my computer was glitching and prevented write access to the Neblio-Qt wallet. Not sure it's related.

**Comment by NeblioTeam** [comment]
This is no longer an issue in recent versions.
