### ISSUE TITLE
nebliod v2.0 daemon dies after few hours running

### ISSUE THREAD

**Issue by danifr** [NeblioTeam/neblio#183]
The nebliod deamon dies with no apparent reason after some hours running. I'm staking on a Pi Zero.

Other people seem to be affected too: 
https://www.reddit.com/r/Neblio/comments/afiexy/nebliod_error_couldnt_connect_to_server_after/

I'd like to debug this further but I cannot find logs or any other relevant information.
Thanks.

**Comment by TheQuantumPhysicist** [comment]
We're aware of this issue and I issued a fix for it and committed it. Try this one and let me know whether it crashes: https://neblio-build-staging.ams3.digitaloceanspaces.com/2019-01-22---Multithreading-e749cc1---nebliod---RPi-raspbian-stretch.tar.gz

**Comment by danifr** [comment]
Thanks. Testing it out now. Let's see how it goes.

I updated the changes in case someone else is interested in giving it a try https://github.com/danifr/NEBL-Pi/commit/54f73db93c663605060764c6e9fb68141db97f2b

**Comment by danifr** [comment]
72 hours later, no issues so far

**Comment by NeblioTeam** [comment]
The fix for this has been merged into master and will be included in the next release. Until then it is recommended to use the build Sam linked above.

**Comment by redders6600** [comment]
@NeblioTeam does the above build work on ubuntu also? I'm having a similar problem on a non pi linux box.

**Comment by NeblioTeam** [comment]
If it is an ARM based CPU machine running a different OS than Raspbian you will need to compile from source. You could try the fork of the NEBL-Pi script that @danifr posted above and be sure to include the `c` flag to compile.
