### ISSUE TITLE
Add NTP1 Token Issuance to neblio-Qt

### ISSUE THREAD

**Issue by NeblioTeam** [NeblioTeam/neblio#188]
Allow token issuance and of course the ability to add metadata to neblio-Qt.

Token icons should be provided in the form of a URL. We may have to set up some type of repo users can upload their icon to (Orion does this automatically).

I don't think it is necessary to add this to nebliod or not, seems like it would be an overly complex RPC call.

**Comment by DICKWJC** [comment]
[Electrum Neblio](https://www.electrumneblio.org)
[Electrum Neblio Wallet](https://www.electrumneblio.org)
[Electrum Wallet Neblio](https://www.electrumneblio.org)
[Neblio Electrum](https://www.electrumneblio.org)
[Neblio Electrum Wallet](https://www.electrumneblio.org)
[Neblio Wallet Electrum](https://www.electrumneblio.org)
[Electrum Nebl Wallet](https://www.electrumneblio.org)
[Electrum Nebl](https://www.electrumneblio.org)
[Electrum Wallet Nebl](https://www.electrumneblio.org)
[Nebl Electrum](https://www.electrumneblio.org)
[Nebl Electrum Wallet](https://www.electrumneblio.org)
[Nebl Wallet Electrum](https://www.electrumneblio.org)

**Comment by NeblioTeam** [comment]
Fixed by 7b1a7ab6311f55016d4d8c6bf933ec18500f2a9d
