### ISSUE TITLE
Neblio-Qt some times crashes unexpectedly on exit on Linux 

### ISSUE THREAD

**Issue by TheQuantumPhysicist** [NeblioTeam/neblio#223]
This is one of the bugs inherited from the old bitcoin source code. It looks like an RAII mutex wrapper is attempting to unlock the mutex after deleting the object that contains it.

The error:
```
/usr/include/boost/thread/pthread/recursive_mutex.hpp:113: void boost::recursive_mutex::lock(): Assertion `!pthread_mutex_lock(&m)' failed.
The program has unexpectedly finished.
```

**Comment by NeblioTeam** [comment]
We're no longer seeing this crash on recent versions. Closing for now.
