### ISSUE TITLE
Shasums?

### ISSUE THREAD

**Issue by Emily7777** [NeblioTeam/neblio#229]
Where can I find the shasums for the latest:
https://github.com/NeblioTeam/neblio/releases

**Comment by NeblioTeam** [comment]
Our automated release system does not currently have the capability of posting the file hashes on the release page, but it is certainly something we want to add. I'll leave this github issue open so that we can investigate how we could add this capability.

**Comment by NeblioTeam** [comment]
Fixed by 0a0aa7e41b2eaa1e631dcd51eeb1020d6928748e

We also added the new formatting with sha256sums to the latest release https://github.com/NeblioTeam/neblio/releases/tag/v2.1.1.1

Going forward this will be taken care of automatically by our release post processing.
