### ISSUE TITLE
Error while loading shared libraries: libminiupnpc.so.8: cannot open shared object file

### ISSUE THREAD

**Issue by nknganda** [NeblioTeam/neblio#23]
Greetings,

Getting the following error on Ubuntu 16.04

`neblio-qt: error while loading shared libraries: libminiupnpc.so.8: cannot open shared object file: No such file or directory`

Please assist. Thanks.

**Comment by NeblioTeam** [comment]
You need to install miniupnpc on your system.

Download and install the "miniupnpc" library (http://miniupnp.free.fr/files/). Version required: 1.6
            Tar -xzvf miniupnpc-1.6.tar.gz
            Cd miniupnpc-1.6
            Make
            Sudo su
            Make install
