### ISSUE TITLE
Error Parsing Token Details for Newly Issued Token in neblio-Qt

### ISSUE THREAD

**Issue by NeblioTeam** [NeblioTeam/neblio#232]
Sometimes after issuing a new token in neblio-Qt the token details are unable to be shown for the new token on the "NTP1 Summary" tab. Clearing the NTP1 Cache in the settings and restarting the wallet fixes the issue.

Screenshot:

![image](https://user-images.githubusercontent.com/29615022/68057216-a519c180-fccb-11e9-8b12-7af3f36ea1e8.png)

**Comment by TheQuantumPhysicist** [comment]
This issue should now be solved. Let's watch if it happens again.
