### ISSUE TITLE
 MinGW Runtime Assertion

### ISSUE THREAD

**Issue by FlashGameDev** [NeblioTeam/neblio#24]
Had a BSOD crash with Neblio running. After reboot I am now getting a MinGW Runtime Assertion everytime I try to start it.
File: src/kernel.cpp, Line 376
Expression: pindex->pprev || pindex->GetBlockHash() == (!fTestNet ? hashGenesisBlock : hashGenesisBlockTestNet)

If I ignore the assertion it says 
Error loading blkindex.dat

Running Windows 7.

Having an option to purge the dat files (and possibly backup the wallet private keys before doing so) would be good in a case like this. I am a programmer and I cannot find where Neblio data files are kept to purge them myself.

**Comment by NeblioTeam** [comment]
Forcibly closing the database that stores the blockchain, due to a crash or other issue, can of course lead to the database becoming corrupt. 

On windows all neblio files are stored in C:\Users\Username\AppData\roaming\neblio

To resolve this issue, shut down neblio. 
Delete all files in that directory **EXCEPT FOR WALLET.DAT**
Restart neblio and it will download a fresh copy of the blockchain.

Adding an option to do this automatically could be done, but it is a pretty rare thing to happen.

**Comment by k3vchun** [comment]
yes, i have the same issue. the nebilo wallet wont open anymore it has the same error

Assertion failed!

File: src/kernel.cpp, Line 376
Expression: pindex->pprev || pindex->GetBlockHash() == (!fTestNet ? hashGenesisBlock : hashGenesisBlockTestNet)

What do I do? I am not a computer expert

**Comment by k3vchun** [comment]
Also, I tried to open up a new wallet on another computer I cant export my wallet.dat to another computer. It won't let me click on export under file

**Comment by NeblioTeam** [comment]
As noted above:

> 
> On windows all neblio files are stored in C:\Users\Username\AppData\roaming\neblio
> 
> To resolve this issue, shut down neblio.
> Delete all files in that directory EXCEPT FOR WALLET.DAT
> Restart neblio and it will download a fresh copy of the blockchain.

**Comment by g4usat** [comment]
Hi, I have the same issue. Wallet doesn't open and shows up a message window "Assertion failed!"
File: src/kernel.cpp, Line 378
Expression: pindex->pprev || pindex->GetBlockHash() == (!fTestNet ? hashGenesisBlock : hashGenesisBlockTestNet)

I've deleted all the files except wallet.dat as mentioned above in the solution. But it still doesn't work. Am still getting the same issue. Attaching the screenshot for your reference. Appreciate if you could help me fix this ASAP.

Thanks!
![neblio wallet error](https://user-images.githubusercontent.com/36013227/45911329-5ff04400-bdd7-11e8-886a-48e6631d32d5.PNG)
