### ISSUE TITLE
Release 2.1.1.1 new Neblio users bug

### ISSUE THREAD

**Issue by toddbeckmann** [NeblioTeam/neblio#255]
This release requires a backup file to be used. New users don't have a backup file and therefore no password to access a backup or to allow changing the password in the first place.

Also if the wallet is hidden it cannot be "unhidden". In Windows, TASK MANAGER is required to END TASK so the wallet can be restarted.

**Comment by NeblioTeam** [comment]
As noted in the reply to the support email you sent the team, it sounds like you may have downloaded the Neblio wallet on your computer some time in the several years and already have a Neblio wallet.dat file on your computer. 

I'll copy and paste the response to your support ticket here in case you did not receive it:

```
It sounds like you already have a wallet on your computer from sometime in the last 2.5 years.
If you are 100% sure this wallet does not contain any NEBL, you can simply delete the wallet.dat
file and then restart the wallet, which will generate a fresh empty wallet file.

To find the wallet.dat file, look in one of the following places:

Windows: %APPDATA%/neblio/wallet.dat
macOS: ~/Library/Application Support/neblio/wallet.dat
```
