### ISSUE TITLE
Windows Wallet Bug

### ISSUE THREAD

**Issue by pumaweb02** [NeblioTeam/neblio#27]
Hello Guys,

I bought some Neblio from an Exchange and transfer them to my Windows Wallet in the middle of the synchronization process. Is been almost 4 days now and the wallet has not finished the sync process. I backup the wallet and installed it on my Mac Pro and is doing the same thing, I try removing all my firewalls and tweaking the router, but nothing since to work.  somebody else had the same problem; that is why I think this is a wallet bug. other wallets work just fine on my windows pc. 

Thank You
Luis

**Comment by NeblioTeam** [comment]
Hi Luis,
A firewall or some type of network settings are blocking your connection to the network. Thousands of users globally are using the windows wallet and connect perfectly fine. Double check any firewall or network settings that could be blocking the connection. The wallet should take only 15-20 minutes to sync the first time on a fast connection.

If you need further help you can email info@nebl.io, but I'm not sure how much help we will be. Troubleshooting firewall/network issues over email, without being there in person for each individual user's setup is quite difficult.
