### ISSUE TITLE
Issue a new NTP1 token dialog box remain open on window preview

### ISSUE THREAD

**Issue by z365air** [NeblioTeam/neblio#275]
Window preview from the taskbar is showing Issue dialog box open whether it is opened or not.

![image](https://user-images.githubusercontent.com/65573983/82751891-08338880-9dc3-11ea-92e9-b121e239bb47.png)

**Comment by NeblioTeam** [comment]
I am unable to reproduce this on Windows 10. Closing for now, please comment if this is still an issue you are having.
