### ISSUE TITLE
Staking appears unstable

### ISSUE THREAD

**Issue by go140point6** [NeblioTeam/neblio#312]
This is a little harder to describe, but observed with 2020-12-21---v3.1.0-25bd742---nebliod---RPi-raspbian-stretch.tar.gz on the latest Raspbian OS (buster) on a Pi4 by issuing the 'getstakinginfo' command over and over.  Have not confirmed on QT ARM version.  The timeline:

1. Stopped v3.0.1, replaced binary with v3.1.0, started wallet and unlocked.  Even though the coins didn't move, coins were suddenly mature-coins:false.  Took about 24 hours before they matured, but staking went true at that time.
2. At about the 30 hour mark, checked 'getstakinginfo' to find enabled:true, staking:false, and all staking-criteria: true.  Immediately ran the command again and suddenly staking:true appeared (and weight came back).
3. Let it sit overnight, and repeated the next day.  Running 'getstakinginfo' over and over every 1-2 seconds appears to show the same phenomenon of sometimes staking:false, sometimes staking:true even though enabled:true and staking-criteria is all true in every case.  Staking weight does eventually increase, but seems much slower to do so then before.

Switch back to v3.0.1 and can't reproduce this issue.  Staking appears completely stable with each 'getstakinginfo' command and staking weight seems to be increasing at a more normal speed.

**Comment by NeblioTeam** [comment]
Fixed in v3.1.1
