### ISSUE TITLE
Neblio screen size on Windows with high resolution screen

### ISSUE THREAD

**Issue by nsudds** [NeblioTeam/neblio#32]
Hi Neblio Team, 

I'm on Windows 10 Lenovo 13 inch laptop with a high-resolution screen and the Neblio wallet screen size is too big for the screen probably due to resolution but not sure exactly.  It may be working with "optimal resolution" that my laptop should be running at not sure. 

Is it possible to make the screen resizable -- I'm sure part of the problem is my settings being different than default but all my other Windows software works fine with this, not sure if anyone else has run into this issue. 

Here's a quick video to show you how it looks on my system
http://screencasts.techsure.ca/2017-11-27_16h06_25.mp4

I tried some options to resize it but that didn't seem to work.  Appreciate the help, it makes it difficult to use the wallet when everything is off the screen. 

Thanks!

**Comment by NeblioTeam** [comment]
Yes this is a bug in the QT window framework we use to draw the window, when on High DPI displays.

I do not have a High DPI display so I cannot reproduce this but some other users have found a solution. See #29

**Comment by nsudds** [comment]
Thanks for the quick reply, that resolved it for me too!

**Comment by nsudds** [comment]
I've been finding this didn't resolve the issue as easily as I had hoped, wonder if this information could be helpful in solving it more permanently for all users. 

http://doc.qt.io/qt-5/highdpi.html

Or if there might be an update to QT that could be applied to fix the issue. 

I'll continue to try to work around it in the meantime but it's a little annoying when trying to see the progress bar or how long until a "reward" because that's at the bottom of the window so it goes off the screen.

**Comment by nsudds** [comment]
Oh also, from another thread with a QT based app, they said you don't need a high resolution display to test -- just set scaling to 200% or something -- this will probably create the same problem on a regular display. 

Hope that is helpful.

**Comment by NeblioTeam** [comment]
Thank you, can you shoot me an email regarding this?

**Comment by NeblioTeam** [comment]
This should finally be fixed by 316ffac and no need to change any of the scaling settings on the .exe anymore. Thanks to @nsudds for testing.

**Comment by nsudds** [comment]
Thanks for resolving this @NeblioTeam -- happy to help!

**Comment by nsudds** [comment]
This is working great now in Windows 10 on the latest release 1.3.0.0  Thank you!
