### ISSUE TITLE
Checksum signature?

### ISSUE THREAD

**Issue by ress23** [NeblioTeam/neblio#33]
What is the SHA-256 checksum of neblio-windows---2017-10-22.zip?

Since the Bitcoin gold core hack I will not install any unverified wallets.

**Comment by NeblioTeam** [comment]
Yes I should start posting these.
neblio-windows---2017-10-22.zip:
bebc9154bdd78d5430839f40b8c405f9bcaed5fe961cc91070cea82c7fbd9c5e

**Comment by ress23** [comment]
Excellent, thank you!

**Comment by ress23** [comment]
I also noticed that the passphrase is shown in full text in the console after -walletpassphrase, other qt wallets hide the text after this command is executed.

**Comment by NeblioTeam** [comment]
Would you mind opening a new issue for that and I'll take a look.
