### ISSUE TITLE
Transaction Table Date Issue After Wallet Import

### ISSUE THREAD

**Issue by NeblioTeam** [NeblioTeam/neblio#345]
Reported by Michael89 in Discord

If a user imports an old wallet (such as after getting a new RPi) all previous transactions will show the date of the import on the transaction table. Including transactions that are weeks, months, or even years old. In this case, the user had transactions from 2017 showing a date of 25/3/21 (the import date).

The transaction detail dialog in this case shows the correct date. 

I took a quick look and I believe this is due to the use of nTimeReceived in transactionrecord.cpp

**Comment by TheQuantumPhysicist** [comment]
Fixed in 658fa8d80983973638e31beba5e315b3d817241c
