### ISSUE TITLE
Error when Recovering wallet via .dat file

### ISSUE THREAD

**Issue by axxcrypt** [NeblioTeam/neblio#347]
Hi team, 

I've downloaded the newest wallet available (V3.2.0) and allowed time to sync with the network + update. Once complete, I closed then reopened the software and then used File>Import Wallet and selected my "wallet.dat" file. After I select it and attempt recovery, it shows me an error in the attached image. What am I doing wrong? I also have a Privkey and PassPhrase but do not see where to enter them in the software for a recovery attempt (it's been a while since I looked at my Neblio!). Please help! 
Thank you

<img width="568" alt="Error after  dat wallet import" src="https://user-images.githubusercontent.com/82565016/114821915-2658fd00-9d76-11eb-9669-a30ae257ecab.PNG">

**Comment by NeblioTeam** [comment]
Unfortunately it seems like the wallet.dat file you are trying to restore is corrupted. 

If you have your private key, you can:

1. Close neblio-Qt
2. Rename the current wallet.dat to wallet.dat.backup or similar
3. Restart neblio-Qt and an empty wallet file will be created automatically
4. Open the Debug Console of the wallet and use the following command to import the private key `importprivkey KEY_HERE`

The wallet will then appear frozen as it looks for NEBL/Tokens that are associated with this private key. Once this completes, assuming this was the only private key you had to import, you should now be done and see your NEBL and tokens.
