### ISSUE TITLE
Compilation error on Ubuntu - windows.h: no such file or directory

### ISSUE THREAD

**Issue by nauvillain** [NeblioTeam/neblio#38]
When I compile I am getting an error - I have installed all the prerequisites listed in the readme-qt.rst.

nico@nico-acer:~/neblio/neblio-1.2$ qmake
Project MESSAGE: Building with UPNP support
Project MESSAGE: Building with DBUS (Freedesktop notifications) support
Removed plural forms as the target language has less forms.
If this sounds wrong, possibly the target language is not set or recognized.
Removed plural forms as the target language has less forms.
If this sounds wrong, possibly the target language is not set or recognized.
Removed plural forms as the target language has less forms.
If this sounds wrong, possibly the target language is not set or recognized.
nico@nico-acer:~/neblio/neblio-1.2$ make
cd /home/nico/neblio/neblio-1.2/src/leveldb && CC=gcc CXX=g++ make OPT="-m64 -pipe -fstack-protector-all -D_FORTIFY_SOURCE=2 -Wl,-z,relro -Wl,-z,now -O2" libleveldb.a libmemenv.a
make[1]: Entering directory '/home/nico/neblio/neblio-1.2/src/leveldb'
g++ -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -m64 -pipe -fstack-protector-all -D_FORTIFY_SOURCE=2 -Wl,-z,relro -Wl,-z,now -O2 -c util/win_logger.cc -o util/win_logger.o
util/win_logger.cc:7:10: fatal error: windows.h: No such file or directory
 #include <windows.h>
          ^~~~~~~~~~~
compilation terminated.
Makefile:212: recipe for target 'util/win_logger.o' failed
make[1]: *** [util/win_logger.o] Error 1
make[1]: Leaving directory '/home/nico/neblio/neblio-1.2/src/leveldb'
Makefile:741: recipe for target '/home/nico/neblio/neblio-1.2/src/leveldb/libleveldb.a' failed
make: *** [/home/nico/neblio/neblio-1.2/src/leveldb/libleveldb.a] Error 2
nico@nico-acer:~/neblio/neblio-1.2$

**Comment by NeblioTeam** [comment]
Did you download the tarball from the 1.2 release? If so this was fixed after 1.2 was released. Clone the HEAD of the repo and that should get past this issue.

**Comment by nauvillain** [comment]
Thanks - this solved that particular issue; I am now getting a new error:

nico@nico-acer:~/nebl/neblio$ make
cd /home/nico/nebl/neblio/src/leveldb && CC=gcc CXX=g++ make OPT="-m64 -pipe -fstack-protector-all -D_FORTIFY_SOURCE=2 -Wl,-z,relro -Wl,-z,now -O2" libleveldb.a libmemenv.a
make[1]: Entering directory '/home/nico/nebl/neblio/src/leveldb'
make[1]: 'libleveldb.a' is up to date.
make[1]: 'libmemenv.a' is up to date.
make[1]: Leaving directory '/home/nico/nebl/neblio/src/leveldb'
cd /home/nico/nebl/neblio; /bin/sh share/genbuild.sh /home/nico/nebl/neblio/build/build.h
g++ -c -m64 -pipe -fstack-protector-all -D_FORTIFY_SOURCE=2 -Wl,-z,relro -Wl,-z,now -O2 -D_REENTRANT -fdiagnostics-show-option -Wall -Wextra -Wno-ignored-qualifiers -Wformat -Wformat-security -Wno-unused-parameter -Wstack-protector -fPIC -DQT_GUI -DBOOST_THREAD_USE_LIB -DBOOST_SPIRIT_THREADSAFE -DQT_DISABLE_DEPRECATED_BEFORE=0 -DUSE_UPNP=1 -DSTATICLIB -DUSE_DBUS -DHAVE_BUILD_INFO -DLINUX -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_DBUS_LIB -DQT_CORE_LIB -Isrc -Isrc/json -Isrc/qt -Isrc/leveldb/include -Isrc/leveldb/helpers -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtDBus -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -Ibuild -isystem /usr/include/libdrm -Ibuild -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -o build/net.o src/net.cpp
src/net.cpp:17:10: fatal error: miniupnpc/miniwget.h: No such file or directory
 #include <miniupnpc/miniwget.h>
          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:2090: recipe for target 'build/net.o' failed
make: *** [build/net.o] Error 1

**Comment by NeblioTeam** [comment]
You are missing miniupnpc it looks like.

sudo apt-get install miniupnpc

**Comment by nauvillain** [comment]
thanks for your help & input!

I did install miniupnpc (which I didn't have indeed) 
But the issue remains - same error. 
And there is no miniupnpc directory in src:
nico@nico-acer:~/nebl/neblio$ ls src
addrman.cpp      init.cpp              netbase.h              scrypt-x86_64.S
addrman.h        init.h                net.cpp                scrypt-x86.S
alert.cpp        json                  net.h                  serialize.h
alert.h          kernel.cpp            noui.cpp               sync.cpp
allocators.h     kernel.h              obj                    sync.h
base58.h         key.cpp               obj-test               test
bignum.h         key.h                 pbkdf2.cpp             threadsafety.h
bitcoinrpc.cpp   keystore.cpp          pbkdf2.h               txdb.h
bitcoinrpc.h     keystore.h            protocol.cpp           txdb-leveldb.cpp
bloom.cpp        leveldb               protocol.h             txdb-leveldb.h
bloom.h          main.cpp              qt                     ui_interface.h
checkpoints.cpp  main.h                rpcblockchain.cpp      uint256.h
checkpoints.h    makefile.bsd          rpcdump.cpp            util.cpp
clientversion.h  makefile.linux-mingw  rpcmining.cpp          util.h
coincontrol.h    makefile.mingw        rpcnet.cpp             version.cpp
compat.h         makefile.osx          rpcrawtransaction.cpp  version.h
crypter.cpp      makefile.unix         rpcwallet.cpp          wallet.cpp
crypter.h        makefile.unix.test    script.cpp             walletdb.cpp
db.cpp           miner.cpp             script.h               walletdb.h
db.h             miner.h               scrypt-arm.S           wallet.h
hash.cpp         mruset.h              scrypt.cpp             zerocoin
hash.h           netbase.cpp           scrypt.h
nico@nico-acer:~/nebl/neblio$

**Comment by nauvillain** [comment]
to be sure, here is the error again:

nico@nico-acer:~/nebl/neblio$ make
cd /home/nico/nebl/neblio/src/leveldb && CC=gcc CXX=g++ make OPT="-m64 -pipe -fstack-protector-all -D_FORTIFY_SOURCE=2 -Wl,-z,relro -Wl,-z,now -O2" libleveldb.a libmemenv.a
make[1]: Entering directory '/home/nico/nebl/neblio/src/leveldb'
make[1]: 'libleveldb.a' is up to date.
make[1]: 'libmemenv.a' is up to date.
make[1]: Leaving directory '/home/nico/nebl/neblio/src/leveldb'
cd /home/nico/nebl/neblio; /bin/sh share/genbuild.sh /home/nico/nebl/neblio/build/build.h
g++ -c -m64 -pipe -fstack-protector-all -D_FORTIFY_SOURCE=2 -Wl,-z,relro -Wl,-z,now -O2 -D_REENTRANT -fdiagnostics-show-option -Wall -Wextra -Wno-ignored-qualifiers -Wformat -Wformat-security -Wno-unused-parameter -Wstack-protector -fPIC -DQT_GUI -DBOOST_THREAD_USE_LIB -DBOOST_SPIRIT_THREADSAFE -DQT_DISABLE_DEPRECATED_BEFORE=0 -DUSE_UPNP=1 -DSTATICLIB -DUSE_DBUS -DHAVE_BUILD_INFO -DLINUX -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_DBUS_LIB -DQT_CORE_LIB -Isrc -Isrc/json -Isrc/qt -Isrc/leveldb/include -Isrc/leveldb/helpers -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtDBus -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -Ibuild -isystem /usr/include/libdrm -Ibuild -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -o build/net.o src/net.cpp
src/net.cpp:17:10: fatal error: miniupnpc/miniwget.h: No such file or directory
 #include <miniupnpc/miniwget.h>
          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:2090: recipe for target 'build/net.o' failed
make: *** [build/net.o] Error 1

**Comment by NeblioTeam** [comment]
If you don't need UPNP, the easiest thing to get you going is probably change in makefile.unix `USE_UPNP:=1` to `USE_UPNP:=0`

**Comment by nauvillain** [comment]
It is odd - I did set it to 0 in src/makefile.unix 
but it still errors at the same place.

**Comment by NeblioTeam** [comment]
Apologies. Instead of changing it to 0, delete or comment that line

**Comment by nauvillain** [comment]
same error :

~/neblio$ make
cd /home/nico/neblio/src/leveldb && CC=gcc CXX=g++ make OPT="-m64 -pipe -fstack-protector-all -D_FORTIFY_SOURCE=2 -Wl,-z,relro -Wl,-z,now -O2" libleveldb.a libmemenv.a
make[1]: Entering directory '/home/nico/neblio/src/leveldb'
make[1]: 'libleveldb.a' is up to date.
make[1]: 'libmemenv.a' is up to date.
make[1]: Leaving directory '/home/nico/neblio/src/leveldb'
cd /home/nico/neblio; /bin/sh share/genbuild.sh /home/nico/neblio/build/build.h
g++ -c -m64 -pipe -fstack-protector-all -D_FORTIFY_SOURCE=2 -Wl,-z,relro -Wl,-z,now -O2 -D_REENTRANT -fdiagnostics-show-option -Wall -Wextra -Wno-ignored-qualifiers -Wformat -Wformat-security -Wno-unused-parameter -Wstack-protector -fPIC -DQT_GUI -DBOOST_THREAD_USE_LIB -DBOOST_SPIRIT_THREADSAFE -DQT_DISABLE_DEPRECATED_BEFORE=0 -DUSE_UPNP=1 -DSTATICLIB -DUSE_DBUS -DHAVE_BUILD_INFO -DLINUX -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_DBUS_LIB -DQT_CORE_LIB -Isrc -Isrc/json -Isrc/qt -Isrc/leveldb/include -Isrc/leveldb/helpers -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtDBus -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -Ibuild -isystem /usr/include/libdrm -Ibuild -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -o build/net.o src/net.cpp
src/net.cpp:17:10: fatal error: miniupnpc/miniwget.h: No such file or directory
 #include <miniupnpc/miniwget.h>
          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:2082: recipe for target 'build/net.o' failed
make: *** [build/net.o] Error 1

**Comment by NeblioTeam** [comment]
Ok that sounds odd.

You have miniupnpc installed, what about `sudo apt-get install libminiupnpc-dev`

**Comment by nauvillain** [comment]
This resolved it! 

Thanks! 
I did install all the required stuff listed in the doc... it either needs an update, or this is something that was in Ubuntu 16.04 and isn't in 17.10.

Thanks again!

**Comment by NeblioTeam** [comment]
The doc most certainly needs an update, if you want to file a separate issue for that it would be a great way to track that work. Glad we got it resolved!
