### ISSUE TITLE
Win10: I can't get wallet to synchronize

### ISSUE THREAD

**Issue by TeisH** [NeblioTeam/neblio#4]
Hi Nebl.io

I'm having difficulties in synchronizing the win wallet to the network.
Am I doing something wrong ?

Br. Teis

![untitled picture](https://user-images.githubusercontent.com/30929348/29214275-fa4d83f8-7ea6-11e7-996f-f2bfb0bf350a.png)

**Comment by TeisH** [comment]
Hello again

The problem was due to firewall restrictions.
The wallet work fine.

Br. Teis

**Comment by NeblioTeam** [comment]
Thanks for the update!
