### ISSUE TITLE
Automatic wallet unlock for staking at startup

### ISSUE THREAD

**Issue by yandreiy** [NeblioTeam/neblio#40]
It would be highly useful to have the option for the wallet to automatically unlock itself at startup for staking purposes. 
It's quite impractical to have to introduce the password every time the walled is opened just for staking.

**Comment by NeblioTeam** [comment]
Unlocking, even just for staking needs your password to decrypt the wallet.dat to get access to your private keys. Adding an option to do this automatically would mean your password would need to be stored somewhere, such as in neblio.conf. This could put your tokens at risk and will never be implemented.

If you understand these risks, you can pass the following to either neblio-qt or nebliod to unlock the wallet, using whatever method you use to start the wallet, **but I would not recommend it.**

`walletpassphrase "passphrase" timeout` where timeout is how long in seconds you want to leave the wallet unlocked.

**Comment by yandreiy** [comment]
Thank you for quick response.
How do you pass the option to the neblio-qt or nebliod?
I tried these but it didn't work (using ubuntu):
 ./neblio-qt walletpassphrase "passphrase" 60
 ./neblio-qt --walletpassphrase "passphrase" 60

**Comment by NeblioTeam** [comment]
You'd need to open the wallet with neblio-qt and then send the RPC command with nebliod

`./neblio-qt`
`./nebliod walletpassphrase "passphrase" 60`
