### ISSUE TITLE
Doc pre-req issue

### ISSUE THREAD

**Issue by nauvillain** [NeblioTeam/neblio#41]
The doc here:
https://github.com/NeblioTeam/neblio/blob/master/doc/readme-qt.rst

currently mentions:
apt-get install qt5-default qt5-qmake qtbase5-dev-tools qttools5-dev-tools \
    build-essential libboost-dev libboost-system-dev \
    libboost-filesystem-dev libboost-program-options-dev libboost-thread-dev \
    libssl-dev libdb++-dev

I was not able to compile without installing:
sudo apt install libminiupnpc-dev

(see #38 )

**Comment by NeblioTeam** [comment]
fixed by bedc93b
