### ISSUE TITLE
Mac Wallet for Neblio - Unable to create

### ISSUE THREAD

**Issue by BillVarwig** [NeblioTeam/neblio#42]
I downloaded the Mac wallet for Neblio and added it to my applications.  However, I am not able to open it.  I get a message that says it can't be opened because it is from an unidentified developer.
![screen shot 2018-01-11 at 8 15 34 pm](https://user-images.githubusercontent.com/35353958/34855175-4a03dc5c-f70c-11e7-9be7-db9f885f3376.png)

**Comment by NeblioTeam** [comment]
This is due to the app not being downloaded from the mac app store. The first time you launch it you need to ctrl+click it and then click open. After than you can start it normally.

**Comment by BillVarwig** [comment]
Wow, thanks a lot for the quick response.  It worked and I can open the
wallet.
