### ISSUE TITLE
File Not Found Error

### ISSUE THREAD

**Issue by wbasterfield** [NeblioTeam/neblio#47]
Hi there

I'm getting the following error when compiling with QT Creator on ubuntu 16.04
error: windows.h: No such file or directory

**Comment by TheQuantumPhysicist** [comment]
Check if this helps: https://github.com/NeblioTeam/neblio/issues/38

**Comment by wbasterfield** [comment]
I cloned the repo as suggested in #38 now get error
"build_config.mk: No such file or directory"

**Comment by TheQuantumPhysicist** [comment]
In the terminal, go to the neblio directory, and run this:

    chmod +x src/leveldb/build_detect_platform

Then try again.

**Comment by wbasterfield** [comment]
That did the trick
Many thanks for your help.!

1 last thing 

My wallet is reporting "Not staking because you don't have enough mature tokens"

How do I fix this ?

**Comment by TheQuantumPhysicist** [comment]
You have to wait for your tokens 24 hours before you can stake them. Please refer to the website/whitepaper for more information on the dynamics of token staking. Mature tokens are tokens that have waited 24 hours in an address after having been transferred to it or after having won the stake reward.

**Comment by NeblioTeam** [comment]
Tokens mature and begin staking after 24 hours.

wbasterfield wrote:
