### ISSUE TITLE
Ubuntu 16.04 not able to start wallet.

### ISSUE THREAD

**Issue by townie** [NeblioTeam/neblio#49]
Looks like this might be the same issue as: https://github.com/NeblioTeam/neblio/issues/20

```./neblio-qt: error while loading shared libraries: libminiupnpc.so.8: cannot open shared object file: No such file or directory```

**Comment by townie** [comment]
YEAH! BITCONNECT WAS USEFUL FOR SOMETHING found this post: https://github.com/bitconnectcoin/bitconnectcoin/issues/3#issuecomment-353803505

Installed deps and everything worked.

```apt-get install  libboost-all-dev libboost-system-dev libboost-filesystem-dev libboost-chrono-dev libboost-program-options-dev libboost-test-dev libboost-thread-dev```

**Comment by NeblioTeam** [comment]
Glad you got it!

**Comment by dbapa** [comment]
I tried install the above libraries... but neblio-qt still complains - "libQt5Widgets.so.5: cannot open shared object file: No such file or directory"

**Comment by TheQuantumPhysicist** [comment]
@dbapa 
If you have installed `qt5-default` package already, then that means you have to fix your environment. That file/library should be found somewhere in `/usr/lib/...`. When you find that with `find /usr/ -iname "libQtWidgets.so*"`, say in `/usr/lib/blabla/`, run this command:
```
export LIBRARY_PATH=/usr/lib/blabla/:${LIBRARY_PATH}
```
Then it should work.

**Comment by dbapa** [comment]
Thanks. I had not installed the qt5-default package.

Installed it and now am able to launch the wallet. Thanks
