### ISSUE TITLE
Limit walletpassphrase timeout to 99999999 and make a value of 0 never re-lock

### ISSUE THREAD

**Issue by XCBatman** [NeblioTeam/neblio#54]
**Hardware**: Raspberry Pi 3
**Operating System Info**: "Raspbian GNU/Linux 9 (stretch)"
**Nebliod Version**: 1.3.1.0

**Issue**
The nebliod process was started by user 'pi' via ssh connection using `nebliod -daemon`. The wallet was unlocked for staking, and the wallet was verified as synced. Using `top`, it was observed that high CPU utilization was occurring for the process, up as high as 110% CPU, but hovering around 105%. 

Using the `ps -Lp <PID> -o pid,ppid,pcpu,pmem,lwp` command, the high CPU utilization was tracked down to a single LWP. Next, using `htop`, enabling tree view, and showing custom thread names (enabled in htop via F2 Setup options), the process "neblio-lock-wa" was showing 100% CPU utilization. See attached screenshot "Nebio_Htop.png" for htop output. 

![neblio_htop](https://user-images.githubusercontent.com/29894544/35188423-24007882-fe03-11e7-96f4-40e51596598e.png)

The number of staking groups was 5. This was observed multiple times, as high CPU utilization would return after restarting nebliod.

**Comment by NeblioTeam** [comment]
For some reason the wallet re-locking thread is using 100% CPU while sleeping. Looking at the code it is not immediately apparent why this is happening unless there is a bug in the version of boost used in this build. Investigating.

v1.2 uses whatever boost is installed on your system.
v1.3+ uses boost 1.55 that is compiled into the binaries and does not use the boost library on your system.

Are you able to reproduce this on v1.2 on your Pi?

**Comment by NeblioTeam** [comment]
After some testing I've found that using a number less than or equal to 99999999 does not cause this. That timeout is just over 3 years, which should be sufficient.

I'm going to repurpose this issue to limit the param to 99999999 and also support a value of 0 never re-locking the wallet.
