### ISSUE TITLE
Fatal Error:  Error opening database

### ISSUE THREAD

**Issue by deuce1307** [NeblioTeam/neblio#60]
I get this message when I try to open my Neblio wallet, which I have never had an issue with until today.

Exception:  St13runtime_error opening database environment Corruption 23 missing files.

Help me.  I can't figure out how to open my wallet.  I try to download it again, I just get the same error message over and over.  I am using a mac.

**Comment by NeblioTeam** [comment]
You need to re-sync the blockchain.

Make sure you have a backup of your wallet.dat

Close neblio-qt

Open Finder, press CMD+Shift+G and paste in `~/Library/Application Support/neblio`

Delete all files here **except for wallet.dat**

Restart neblio-qt and wait for the blockchain to resync

**Comment by deuce1307** [comment]
Thank you. I am re-syncing now. I have another question. Please pardon my ignorance. When the wallet has finished re-syncing, should I need to use my backup of my wallet.dat or should my wallet just open?

I REALLY appreciate your help.

Patrick

Sent from my iPhone

On Jan 21, 2018, at 5:15 PM, Neblio Team <notifications@github.com<mailto:notifications@github.com>> wrote:


You need to re-sync the blockchain.

Make sure you have a backup of your wallet.dat

Close neblio-qt

Open Finder, press CMD+Shift+G and paste in ~/Library/Application Support/neblio

Delete all files here except for wallet.dat

Restart neblio-qt and wait for the blockchain to resync

**Comment by deuce1307** [comment]
Hi again, I have a new issue. I deleted all files in the folder but the wallet.dat, and the Neblio wallet started to sync. It did so for several minutes, then gave me this:

Exception:  St13runtime_error
CBD() : can’t open database file wallet.dat, error -30974
neblio in ProcessMessages()

[image1.jpeg]

[image2.jpeg]

Any idea where I should go from here?

Thanks for anything you can give me.

Sent from my iPhone

On Jan 21, 2018, at 5:15 PM, Neblio Team <notifications@github.com<mailto:notifications@github.com>> wrote:


You need to re-sync the blockchain.

Make sure you have a backup of your wallet.dat

Close neblio-qt

Open Finder, press CMD+Shift+G and paste in ~/Library/Application Support/neblio

Delete all files here except for wallet.dat

Restart neblio-qt and wait for the blockchain to resync

**Comment by NeblioTeam** [comment]
This means the wallet.dat is unable to be opened. 
Make sure the permissions on that file are readable.

If permissions are readable, this could mean the file is corrupt. Copy your backup file into the directory and hopefully your backup is good. If not, try using a backup from a previous day, as your hard drive may be failing.

**Comment by deuce1307** [comment]
Thanks again for your help. I’ll probably be reaching out again at some point. I don’t have a lot of confidence in my backup file. Seriously though, regardless of the outcome of this, I really appreciate you trying to help me.

Patrick

Sent from my iPhone

On Jan 21, 2018, at 6:56 PM, Neblio Team <notifications@github.com<mailto:notifications@github.com>> wrote:


This means the wallet.dat is unable to be opened.
Make sure the permissions on that file are readable.

If permissions are readable, this could mean the file is corrupt. Copy your backup file into the directory and hopefully your backup is good. If not, try using a backup from a previous day, as your hard drive may be failing.
