### ISSUE TITLE
Wallet: Addresses not legible because column has fixed width

### ISSUE THREAD

**Issue by sebrock** [NeblioTeam/neblio#62]
In the "Receive tokens" and Address Book screen, the Addresses are not entirely legible because column "Address" has fixed width- 
It should be resizable, so an entire Address can be seen.

Came to my attention running v1.3.1.0 on Raspian.

![20180124_nebl-pi_issue-addrbook-colwidth](https://user-images.githubusercontent.com/156824/35357854-13a07f1e-0155-11e8-878b-3e4199a44993.png)

**Comment by TheQuantumPhysicist** [comment]
Actually, the column size is resizable, just hold it from the far right side, not from the middle. I just tried it now.

**Comment by sebrock** [comment]
My bad.
Thanks!
