### ISSUE TITLE
Getting st13runtime_error in ubuntu

### ISSUE THREAD

**Issue by nauvillain** [NeblioTeam/neblio#66]
I had a working Neblio wallet until today; 
now I am getting:

************************
EXCEPTION: St13runtime_error       
init_blockindex(): error opening database environment Corruption: no meta-nextfile entry in descriptor       
neblio in Runaway exception       

I have reinstalled in a new folder, with the latest git clone, thinking it may be due to a corrupt file - but I got the same error, making me think it's a conflict with an Ubuntu update. 

Let me know if you need me to run further tests to debug this,

thanks!

**Comment by NeblioTeam** [comment]
The database got corrupted, either due to a crash, unexpected shutdown, or a failing hard drive. 

To recover you simply need to delete the database and resync the blockchain. 
Close the wallet. 
Delete everything in ~/.neblio/ **EXCEPT FOR WALLET.DAT**
Restart the wallet and let it resync.

**Comment by nauvillain** [comment]
Please close this - I forgot to rename ~/.neblio , and the corrupt file was in there. My apologies!

**Comment by nauvillain** [comment]
ah - refreshing the page helps :)
