### ISSUE TITLE
Notification from the wallet when staking was successfull

### ISSUE THREAD

**Issue by veithfer** [NeblioTeam/neblio#8]
It would be convenient to receive a notification (maybe on the phone or daily via mail) with the info how many NEBL have been staked. Or just a notification (macOS) via the desktop.
Maybe an audio notification is also an option

**Comment by NeblioTeam** [comment]
macOS desktop notifications were broken. I just fixed them. You will not get a notification on any sent or received transaction, including a successful stake. I am going to close this issue, if you want further enhancement, please open a new issue.
