### ISSUE TITLE
Wallet is not starting error in the screenshot.. please help

### ISSUE THREAD

**Issue by 3bu1kanyal** [NeblioTeam/neblio#87]
![error](https://user-images.githubusercontent.com/37067338/36967786-bbf8d9d6-2086-11e8-883e-6426048e922c.JPG)

**Comment by JamieD1** [comment]
Delete everything in %appdata%/neblio except your wallet.dat

**Comment by NeblioTeam** [comment]
Thanks Jamie.

Also see answer for #24
