### ISSUE TITLE
Initiate a thread-safe singleton logging system

### ISSUE THREAD

**Issue by TheQuantumPhysicist** [NeblioTeam/neblio#89]
The current logging system uses `printf` with a redirect to a file. This has many problems, including that it's not thread-safe and it doesn't have any time stamping by default or logging levels. A better logging system has to be made. Initially, we can think of a singleton that's derived from boost log.

**Comment by DICKWJC** [comment]
[Electrum Neblio](https://www.electrumneblio.org)
[Electrum Neblio Wallet](https://www.electrumneblio.org)
[Electrum Wallet Neblio](https://www.electrumneblio.org)
[Neblio Electrum](https://www.electrumneblio.org)
[Neblio Electrum Wallet](https://www.electrumneblio.org)
[Neblio Wallet Electrum](https://www.electrumneblio.org)
[Electrum Nebl Wallet](https://www.electrumneblio.org)
[Electrum Nebl](https://www.electrumneblio.org)
[Electrum Wallet Nebl](https://www.electrumneblio.org)
[Nebl Electrum](https://www.electrumneblio.org)
[Nebl Electrum Wallet](https://www.electrumneblio.org)
[Nebl Wallet Electrum](https://www.electrumneblio.org)

**Comment by TheQuantumPhysicist** [comment]
This was already accomplished with spdlog
