### ISSUE TITLE
publish build directions for linux/windows/mac in README

### ISSUE THREAD

**Issue by NeblioTeam** [NeblioTeam/neblio#9]
Need to compile my own notes into a readable and followable set of directions for compilation on each platform

**Comment by martinsmid** [comment]
Do you have some draft of the notes where we can contribute ? I am trying to run this on ubuntu 16.04. Found dependency on `libboost-program-options` for the daemon and `libminiupnpc` for the "qt" part but installing the latter didn't help. Now the daemon cries for `libdb_cxx-5.3.so`

**Comment by NeblioTeam** [comment]
See if this helps: https://github.com/NeblioTeam/neblio/blob/master/doc/readme-qt.rst

**Comment by wbasterfield** [comment]
The manual build produces as similar result.
I also ram make as admin user in this case

cd /home/warren/Downloads/neblio-master/src/leveldb && CC=gcc CXX=g++ make OPT="-m64 -pipe -fstack-protector-all -D_FORTIFY_SOURCE=2 -Wl,-z,relro -Wl,-z,now -O2" libleveldb.a libmemenv.a
make[1]: Entering directory '/home/warren/Downloads/neblio-master/src/leveldb'
/bin/sh: 1: ./build_detect_platform: Permission denied
Makefile:18: build_config.mk: No such file or directory
make[1]: *** No rule to make target 'build_config.mk'.  Stop.
make[1]: Leaving directory '/home/warren/Downloads/neblio-master/src/leveldb'
Makefile:702: recipe for target '/home/warren/Downloads/neblio-master/src/leveldb/libleveldb.a' failed
make: *** [/home/warren/Downloads/neblio-master/src/leveldb/libleveldb.a] Error 2

**Comment by TheQuantumPhysicist** [comment]
In the terminal, go to the neblio directory, and run this:

    chmod +x src/leveldb/build_detect_platform

Then try again.

**Comment by NeblioTeam** [comment]
This will be addressed in #1
