### ISSUE TITLE
Wallet freezing on entering an amount to send - Fedora 27

### ISSUE THREAD

**Issue by seanbailey** [NeblioTeam/neblio#90]
Under the 'Send tokens' tab, clicking within the 'Amount' input box freezes the wallet. This is also the case, if the + or - buttons are clicked.

If the currency (NEBL/mNEBL) is selected from the dropdown prior to entering an amount, it is then possible to enter an amount in the input box without the wallet freezing.

OS: Linux Fedora 27 (4.15.6-300.fc27.x86_64)
Package: neblio-ubuntu16.04---2018-01-20.tar.gz 

Attempted to compile neblio-qt using the latest source code. Compiled using OpenSSL1.0.2 (OpenSSL1.1.0 pre-installed on Fedora). Running the compiled neblio-qt opened the slash screen and then exited with "Segmentation fault (core dumped)" in the terminal. Note some package dependencies differ on Fedora to Ubuntu when compiling. The following packages were installed:

qt-devel 
qt-doc 
qt-creator

**Comment by classic0** [comment]
**Installed packages suggested in build-unix.txt:** 

Package: build-essential
Version: 12.3

Package: libssl-dev
Version: 1.1.0f-3+deb9u1

Package: libdb++-dev
Version: 5.3.1

Package: libboost-all-dev
Version: 1.62.0.1

Package: libqrencode-dev
Version: 3.4.4-1+b2


/////////////
_I had a bigNUM issue so I went for not so recent libssl version_ 

libssl1.0-dev/stable,stable,now 1.0.2l-2+deb9u2 amd64 [installed]
  Secure Sockets Layer toolkit - development files

libssl1.0.0/jessie-backports,now 1.0.2l-1~bpo8+1 amd64 [installed]
  Secure Sockets Layer toolkit - shared libraries

libssl1.0.2/stable,stable,now 1.0.2l-2+deb9u2 amd64 [installed]
  Secure Sockets Layer toolkit - shared libraries

libssl1.1/stable,stable,now 1.1.0f-3+deb9u1 amd64 [installed]
  Secure Sockets Layer toolkit - shared libraries

/////////////

**Packages suggested for Debian in readme-qt.rst file:** 

sudo     apt-get install qt5-default qt5-qmake qtbase5-dev-tools qttools5-dev-tools         build-essential libboost-dev libboost-system-dev         libboost-filesystem-dev libboost-program-options-dev libboost-thread-dev         libssl-dev libdb++-dev libminiupnpc-dev

libboost-dev is already the newest version (1.62.0.1).
libboost-filesystem-dev is already the newest version (1.62.0.1).
libboost-program-options-dev is already the newest version (1.62.0.1).
libboost-system-dev is already the newest version (1.62.0.1).
libboost-thread-dev is already the newest version (1.62.0.1).
build-essential is already the newest version (12.3).
libdb++-dev is already the newest version (5.3.1).
libminiupnpc-dev is already the newest version (1.9.20140610-4).
qt5-default is already the newest version (5.7.1+dfsg-3+b1).
qt5-qmake is already the newest version (5.7.1+dfsg-3+b1).
qtbase5-dev-tools is already the newest version (5.7.1+dfsg-3+b1).
qttools5-dev-tools is already the newest version (5.7.1-1)
The following packages will be REMOVED:
  libssl1.0-dev
The following NEW packages will be installed:
  libssl-dev


///////

I also had to install
Package: lib64z1-dev:i386
Version: 1:1.2.8.dfsg-5

Compiled by executing
make
in neblio-1.4 folder

Kernel version: 4.9.0-6-amd64
Qt Version: 5.7.1
